### ISSUE TITLE
Unhandled exception when running .exe

### ISSUE THREAD

**Issue by cptkel** [DanielHazzard/FFXI-Rollbot-v2#10]
I have downloaded the zip and made a folder on desktop; moved crb_addon folder to /addons

I get this error:
![image](https://user-images.githubusercontent.com/51523520/73502176-24d02e80-4396-11ea-995c-bce1af3570c1.png)

**Comment by DanielHazzard** [comment]
Make sure you have the following: 

**VC++ 2010 x86 - http://download.microsoft.com/download/5/B/C/5BC5DBB3-652D-4DCE-B14A-475AB85EEF6E/vcredist_x86.exe
VC++ 2012 x86 - http://download.microsoft.com/download/1/6/B/16B06F60-3B20-4FF2-B699-5E9B7962F9AE/VSU3/vcredist_x86.exe 
VC++ 2013 x86 - http://download.microsoft.com/download/2/E/6/2E61CFA4-993B-4DD4-91DA-3737CD5CD6E3/vcredist_x86.exe 
VC++ 2015 x86 - https://download.microsoft.com/download/9/3/F/93FCF1E7-E6A4-478B-96E7-D4B285925B00/vc_redist.x86.exe**

**Comment by cptkel** [comment]
Yes that was the problem. I got a file check from epic NPC website and got
it running. Thank you

**Comment by DanielHazzard** [comment]
Wonderful, glad to hear.
