### ISSUE TITLE
crb_addon loads, but does nothing

### ISSUE THREAD

**Issue by BBKenneth** [DanielHazzard/FFXI-Rollbot-v2#4]
Hi. Thanks for an awesome application. I would love to use the crb_addon though. It loads fine, but neither crb toggle or crb start is working. As in no response. No error message, no nothing. Still addon loads fine on launch, and unloads when i close the appliaction itself. //crb toggle would be amazing to do, and afaik this was also intended.

**Comment by DanielHazzard** [comment]
I'll look into it.
