### ISSUE TITLE
Check for reset on snake is slower than double up

### ISSUE THREAD

**Issue by ghost** [DanielHazzard/FFXI-Rollbot-v2#7]
I see a few issues revolving around 11's. Personally never seen this. However, I have noticed be it lag or what not, if it resets ja's either by manual intervention (wildcard) or random deal from the bot. This will cause the bot to go back to the start and just double up before the check for snake eyes resetting. I have not noticed this when set to snakes on 10 but always below (I fish for 11's and have to just manual do it at the start)

Could you add a check delay for snakes eyes reset?

**Comment by DanielHazzard** [comment]
I'll look into this.
